<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_All
 */
?>
<?php
/**
 * @var \Magento\Backend\Block\Template $block
 */
?>
<script>
    require([
        "jquery"
    ], function($){
        $(document).ready(function () {
            $('a[href*="https://magerubik.com"], a[href*="http://magerubik.com"], a[href*="https://marketplace.magento.com"]')
                .attr('target', '_blank');
        });
    });
</script>
