<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_All
 */
?>
<?php
/** @var \Magerubik\All\Block\Adminhtml\Messages $block */
$messages = $block->getMessages();
?>
<?php if (!empty($messages)): ?>
    <?php foreach ($messages as $message): ?>
        <div class="messages mrall-unsubscribe">
            <div class="message message-success success">
                <div data-ui-id="messages-message-success"><?= /* @noEscape */ $message;?></div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
